id: P008090
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:00:53.226873
source_metadata:
  id: bdr:W1KG11762
  title: རྭ་སྟོད་བསྡུས་གྲྭ། （ལྷ་ས་པར་མ།）
  author: ''
  volumes:
    9e87693f75db453e899cb02d1a5c247e:
      image_group_id: I1KG11764
      title: Volume 1 of rwa stod bsdus grwa/ (lha sa par ma/)
      volume_number: 1
      total_pages: 588
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
