id: P008090
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11762
  title: རྭ་སྟོད་བསྡུས་གྲྭ། （ལྷ་ས་པར་མ།）
  author: ''
  volumes:
    4f9d59a4d8f54069a3e23d454fc5ccf6:
      image_group_id: I1KG11764
      title: ''
      volume_number: 1
      total_pages: 588
ebook_metadata:
  title: རྭ་སྟོད་བསྡུས་གྲྭ། （ལྷ་ས་པར་མ།）
  author: ''
  sku: P008090
  cover: cover.jpg
  layers:
  - pagination
