id: I47922C9B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:41:18+00:00'
last_modified: '2022-06-09T04:25:34.929463+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11762
  title: རྭ་སྟོད་བསྡུས་གྲྭ། （ལྷ་ས་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    56C6:
      image_group_id: I1KG11764
      title: Volume 1 of rwa stod bsdus grwa/ (lha sa par ma/)
      total_pages: 588
      order: 1
      base_file: 56C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
