id: I47922C9B
legacy_id: P008090
ocr_import_info:
  bdrc_scan_id: W1KG11762
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:37:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:04:44.149436+00:00'
last_modified: 2022-08-31 11:05:08.016517
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11762
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11762
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྭ་སྟོད་བསྡུས་གྲྭ། （ལྷ་ས་པར་མ།）
  author: ཤངས་པ་ཀུན་མཁྱེན་མཆོག་ལྷ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.5830536812953858
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I1KG11764:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11764
      total_pages: 588
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11764.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5830536812953858
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
